Resources:
  TestRegistryPolicy:
    Type: 'AWS::ECR::RegistryPolicy'
    Properties:
      PolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: UpdatedRegistryPolicy
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::928814396842:root'
            Action:
                - 'ecr:CreateRepository'
                - 'ecr:ReplicateImage'
		- 'ecr:BatchCheckLayerAvailability'
		- 'ecr:BatchDeleteImage'
		- 'ecr:BatchGetImage'
		- 'ecr:CompleteLayerUpload'
		- 'ecr:DeleteLifecyclePolicy'
		- 'ecr:DeleteRepository'
		- 'ecr:DeleteRepositoryPolicy'
		- 'ecr:DescribeImages'
		- 'ecr:DescribeRepositories'
		- 'ecr:GetDownloadUrlForLayer'
		- 'ecr:GetLifecyclePolicy'
		- 'ecr:GetLifecyclePolicyPreview'
		- 'ecr:GetRepositoryPolicy'
		- 'ecr:InitiateLayerUpload'
		- 'ecr:ListImages'
		- 'ecr:PutImage'
		- 'ecr:PutLifecyclePolicy'
		- 'ecr:SetRepositoryPolicy'
		- 'ecr:StartLifecyclePolicyPreview'
		- 'ecr:UploadLayerPart'
            Resource: 'arn:aws:ecr:us-west-2:928814396842:repository/*'
